# Copyright 2017-present The Material Motion Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

http_archive(
    name = "build_bazel_rules_apple",
    url = "https://github.com/bazelbuild/rules_apple/archive/0.2.0.zip",
    strip_prefix = "rules_apple-0.2.0",
    # Generated by running: openssl sha -sha256 <path to zip>
    sha256 = "4ae91e15243fbe39a02b7e9a1bba6de50c5554443a30c5587cfeff7404dfdd56"
)

http_archive(
    name = "bazel_ios_warnings",
    url = "https://github.com/material-foundation/bazel_ios_warnings/archive/v2.0.0.zip",
    strip_prefix = "bazel_ios_warnings-2.0.0",
    # Generated by running: openssl sha -sha256 <path to zip>
    sha256 = "199f1b1726ca561d5dedcb3876094a9604f603dc8d737b0e6b8866a70dc8a90d"
)
